// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtMJSS6uLD4qcNjxVDg73t2ljJgpgIOHU',
    appId: '1:888618663086:web:92c80c1d95d86f3958c13f',
    messagingSenderId: '888618663086',
    projectId: 'chatappttute-43e02',
    authDomain: 'chatappttute-43e02.firebaseapp.com',
    storageBucket: 'chatappttute-43e02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGCIiRyLya_1cXp9SGvqCdzp0Ean641as',
    appId: '1:888618663086:android:44dd6fe3af80864f58c13f',
    messagingSenderId: '888618663086',
    projectId: 'chatappttute-43e02',
    storageBucket: 'chatappttute-43e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0m_9vPGJHeN29oO7ikbFOMbeyh5qdD38',
    appId: '1:888618663086:ios:2a214cf137633cf658c13f',
    messagingSenderId: '888618663086',
    projectId: 'chatappttute-43e02',
    storageBucket: 'chatappttute-43e02.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0m_9vPGJHeN29oO7ikbFOMbeyh5qdD38',
    appId: '1:888618663086:ios:2a214cf137633cf658c13f',
    messagingSenderId: '888618663086',
    projectId: 'chatappttute-43e02',
    storageBucket: 'chatappttute-43e02.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtMJSS6uLD4qcNjxVDg73t2ljJgpgIOHU',
    appId: '1:888618663086:web:f08cdd355b2e55f058c13f',
    messagingSenderId: '888618663086',
    projectId: 'chatappttute-43e02',
    authDomain: 'chatappttute-43e02.firebaseapp.com',
    storageBucket: 'chatappttute-43e02.firebasestorage.app',
  );
}
